---
homebrew_root: /opt/homebrew
#homebrew_root: /usr/local

# vars file for homebrew
homebrew_taps:
  # - homebrew/dupes
  # - homebrew/versions
  # - homebrew/boneyard
  # - homebrew/binary
  # - drone/drone
  - johanhaleby/kubetail
  - laishulu/homebrew # for macism
  - daipeihust/tap # for im-select
  # - sfus/customs

homebrew_my_packages: []
  # - name: sfus/customs/utf8proc
  # - { name: sfus/customs/tmux, state: head }

homebrew_packages:
  - name: ansible
  - name: coreutils # to install realpath for tmux-powerline
  - name: fd
  - name: fzf
  - name: fontforge
  - name: git
  - name: ghq
  - name: go
  - name: grep
  - name: hub
  - name: less
  - name: mas
  # - name: npm
  # - name: peco
  # - name: python
  - name: python3
  - name: reattach-to-user-namespace
  - name: ripgrep
  - name: the_silver_searcher
  - name: tig
  - name: tmux
  - name: vifm
  - name: wget
  - name: zsh

homebrew_other_packages:
  - name: aspell
  - name: bat
  - name: cmigemo
  - name: ctags
  # - name: drone@0.8.6
  - name: dive
  - name: exiftool
  - name: ffmpeg
  - name: flyway
  - name: gawk
  - name: gcc
  # - name: gdb
  # - { name: global, install_options: [ with-ctags, with-pygments ] }
  - name: gnu-time
  # - name: google-cloud-sdk
  - name: gradle
  - name: grep
  - name: groovy
  - name: htop
  - name: hugo
  - name: imagemagick
  - name: im-select
  - name: jsonnet
  - name: jq
  - name: kotlin
  - name: krew
  - name: kubernetes-cli
  - name: kubectx
  - { name: kubetail, install_options: [ with-short-names ] }
  - name: kubeseal
  - name: kustomize
  - name: kind
  - name: lua
  - name: lazydocker
  - name: lesspipe
  - name: libsecret
  - name: macism
  - name: markdownlint-cli
  - name: maven
  - name: mecab
  - name: mecab-ipadic
  - { name: mysql, install_options: client-only }
  - name: ninja
  - name: nkf
  - name: openssl
  - name: pngpaste
  - name: plantuml
  - name: protobuf
  - name: redis
  # - name: rcmdnk/rcmdnkpac/parse-plist
  - name: ripgrep
  - name: source-highlight
  - name: sqlite
  - name: ssh-copy-id
  - name: stern
  - name: swig
  # - name: k1LoW/tap/tbls
  - name: tcl-tk
  # - name: tmux-xpanes
  - name: ttyrec
  # - name: utf8proc
  - name: translate-shell
  - name: w3m
  - name: yq
  - name: zlib
